on: [workflow_call]
jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1.0.2 
        with:
            library-manager: update
            compliance: strict
    
