name: arduino-lint
on: [workflow_dispatch, push]
jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1.0.2 
        with:
            project-type: library
            library-manager: update
            compliance: strict
    
