name: arduino/arduino-lint-action
run-name: ${{ github.actor }} Check Arduino projects for problems
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/arduino-lint-action@v1.0.2

 
          
